name: build_cuda

on:
  push:
    paths:
      - .github/workflows/build_cuda.yml
  workflow_dispatch: {}

env:
  gmxversion: "2026.2"
  gmxcompileto: C:/FOSS/gromacs_262
  dependhome: C:/FOSS/Dependencies
  dependpath: C:/FOSS/Dependencies/vcpkg_installed/x64-windows

jobs:
  build:
    runs-on: windows-2025
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install FFTW, hwloc, OpenBLAS
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force ${{ env.dependhome }}
          Set-Location ${{ env.dependhome }}
          vcpkg new --application
          vcpkg add port fftw3[avx2,threads]
          vcpkg add port hwloc
          vcpkg add port openblas[threads]
          vcpkg install --overlay-ports=${{ github.workspace }}\vcpkg_overlay
          Get-ChildItem "${{ env.dependpath }}\bin"

      - name: Install CUDA Toolkit
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.35
        with:
          cuda: "13.1.0"
      
      - name: Copy BuildCustomizations
        shell: pwsh
        run: |
          Copy-Item -Path "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\extras\visual_studio_integration\MSBuildExtensions\*" -Destination "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations\" -Force
          Copy-Item -Path "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\extras\visual_studio_integration\MSBuildExtensions\*" -Destination "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations\" -Force
          Get-ChildItem "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\bin\x64"

      - name: Download Gromacs
        shell: bash
        env:
          gmxdownloadlink: https://ftp.gromacs.org/gromacs/gromacs-2026.2.tar.gz
          gmxmd5hash: "74c859cb7f53919f9c7760c287b43323"
        run: |
          curl -Lfo gromacs_src.tar.gz ${{ env.gmxdownloadlink }}
          echo "${{ env.gmxmd5hash }}  gromacs_src.tar.gz" | md5sum -c
          tar xf gromacs_src.tar.gz

      - name: Compile GROMACS CUDA
        shell: cmd
        run: |
          cd gromacs-${{ env.gmxversion }}
          mkdir build
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release "-DCMAKE_INSTALL_PREFIX=${{ env.gmxcompileto }}" "-DCMAKE_PREFIX_PATH=${{ env.dependpath }}" "-DGMX_GPU=CUDA" "-DGMX_SIMD=AVX2_256" "-DGMX_HWLOC=ON" ..
          cmake --build .
          cmake --install .
          cd ..
          cd ..
          rd /S /Q gromacs-${{ env.gmxversion }}

      - name: Checksum
        shell: bash
        run: |
          echo "BUILDDATE=$(date '+%b%d')" >> $GITHUB_ENV
          cd `cygpath "${{ env.gmxcompileto }}"/bin`
          sha256sum gmx.exe | tee gmx.exe.sha256

      - name: Extra force fields
        shell: bash
        run: |
          cd `cygpath "${{ env.gmxcompileto }}"/share/gromacs/top`
          curl -Lo 'charmm36-feb2026_cgenff-5.0.ff.tgz' 'https://mackerell.umaryland.edu/download.php?filename=CHARMM_ff_params_files/charmm36-feb2026_cgenff-5.0.ff.tgz'
          echo 'c2b0c70e21cced150528ee25d205e5bd3367a5e55e85c2ff0403911980528151  charmm36-feb2026_cgenff-5.0.ff.tgz' | sha256sum -c
          tar -x --ungzip -f charmm36-feb2026_cgenff-5.0.ff.tgz
          sed -i '1cCHARMM36 all-atom force field (February 2026)' charmm36-feb2026_cgenff-5.0.ff/forcefield.doc
          curl -Lo 'charmm36-feb2026_ljpme_cgenff-5.0.ff.tgz' 'https://mackerell.umaryland.edu/download.php?filename=CHARMM_ff_params_files/charmm36-feb2026_ljpme_cgenff-5.0.ff.tgz'
          echo 'b2221dcba73066b6b5c30a52b9894216d03ea6c3e68206d9ce43857dd8116c21  charmm36-feb2026_ljpme_cgenff-5.0.ff.tgz' | sha256sum -c
          tar -x --ungzip -f charmm36-feb2026_ljpme_cgenff-5.0.ff.tgz
          sed -i '1cCHARMM36 LJ-PME all-atom force field (February 2026)' charmm36-feb2026_ljpme_cgenff-5.0.ff/forcefield.doc
          rm -f charmm36-feb2026_cgenff-5.0.ff.tgz charmm36-feb2026_ljpme_cgenff-5.0.ff.tgz

      - name: Copy DLLs and Test
        continue-on-error: true
        shell: pwsh
        run: |
          Copy-Item -Force -Path "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\bin\x64\cufft64_*.dll" -Destination "${{ env.gmxcompileto }}\bin\"
          Copy-Item -Force -Path "${{ env.dependpath }}\bin\*.dll" -Destination "${{ env.gmxcompileto }}\bin\"
          Set-Location ${{ env.gmxcompileto }}\bin
          Remove-Item -Force -Path fftw3l.dll,fftw3.dll
          .\gmx.exe -version

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        if: ${{ success() }}
        with:
          name: GROMACS-${{ env.gmxversion }}_${{ env.BUILDDATE }}_GPU_Windows-AMD64-AVX2_CUDA1310_msvc
          path: ${{ env.gmxcompileto }}
